Repository clamsproject/clams-deploy, pull requests merged in 2024-02, with the labels that each got.

#1 🍪 Cookiecutter template
  README.md
  cookiecutter.json
  {{ cookiecutter.project_slug }}/deploy.yml
  {{ cookiecutter.project_slug }}/hpa.yml
  {{ cookiecutter.project_slug }}/service.yml
Labels: enhancement ➕, documentation 📜

#2 📰 Scenes With Text
  app-swt-detection/deploy.yml
  app-swt-detection/hpa.yml
  app-swt-detection/service.yml
Labels: :sparkles:N, enhancement ➕

#3 3⃣️ SWT v3
  app-swt-detection-v3/deploy.yml
  app-swt-detection-v3/hpa.yml
  app-swt-detection-v3/service.yml
Labels: enhancement ➕
